### ISSUE TITLE
doesn't like version: 1 

### ISSUE THREAD

**Issue by StevenBecke** [skradel/Zetetic.Ldap#1]
my ldifs start with a line "version: 1"

the reader chokes on this - easily fixed in my copy of the source

**Comment by skradel** [comment]
Fixed - LdifReader will skip any line not starting with 'dn:' when there is no open entry being read.  This makes the parser extremely tolerant (perhaps excessively tolerant?) of any sort of pre- or intra-entry content in the LDIF.
