### ISSUE TITLE
Unable to enumerate Entry attributes

### ISSUE THREAD

**Issue by dcleaver** [skradel/Zetetic.Ldap#10]
Attributes on the Entry class are not enumerable - you have to know the attribute names in advance and call GetAttrStringValues() with the exact name of the attribute.

Is there a way to loop over attributes?

**Comment by skradel** [comment]
Just added an an indexer property for 'entry["cn"]' reads and writes (although this does not currently mesh with MutableEntry change tracking), and implemented IEnumerable<Attr> on Entry -- please let me know how this works for you.

**Comment by dcleaver** [comment]
Works a treat. Thanks for the quick response and code change!
