### ISSUE TITLE
attributes cannot be null

### ISSUE THREAD

**Issue by StevenBecke** [skradel/Zetetic.Ldap#3]
looks like the fix to parse nulls causes an error elsewhere -

in Entry.cs line 130             if (attrValue == null)
                throw new ArgumentNullException("attrValue");

taking a quick glance at the LDIF spec it seems to refer to entries like this as zero length entries - I'm not sure if they're implying that they should not be null. I'm just going to change my copy of the code to return empty strings for now for these entries since it will meet my needs

**Comment by skradel** [comment]
I agree with your interpretation of the LDIF spec and have updated.
