### ISSUE TITLE
Requires 2 newlines at the end of each LDIF File

### ISSUE THREAD

**Issue by Casebash** [skradel/Zetetic.Ldap#4]
My understanding of the standard was that only one should be required: http://tools.ietf.org/html/rfc2849

**Comment by skradel** [comment]
Fixed just now... LdifEntryReader.ReadEntry needed to check for a complete entry on hand even though the underlying LdifReader was out of content.

**Comment by Casebash** [comment]
Wow, thanks for such a quick fix.

**Comment by skradel** [comment]
No problem, thanks for reporting the bug.  Best way for this library to improve beyond the LDIF I've already fed it for testing.
