### ISSUE TITLE
Can't parse file from the technical specification

### ISSUE THREAD

**Issue by Casebash** [skradel/Zetetic.Ldap#5]
Below I have pasted an ldif file from the technical specification. http://tools.ietf.org/html/rfc2849. The parser fails to parse it correctly. (Unfortunately it doesn't display very well here)

dn:: b3U95Za25qWt6YOoLG89QWlyaXVz
# dn:: ou=<JapaneseOU>,o=Airius

objectclass: top
objectclass: organizationalUnit
ou:: 5Za25qWt6YOo
# ou:: <JapaneseOU>

ou;lang-ja:: 5Za25qWt6YOo
# ou;lang-ja:: <JapaneseOU>

ou;lang-ja;phonetic:: 44GI44GE44GO44KH44GG44G2
# ou;lang-ja:: <JapaneseOU_in_phonetic_representation>

ou;lang-en: Sales
description: Japanese office

dn:: dWlkPXJvZ2FzYXdhcmEsb3U95Za25qWt6YOoLG89QWlyaXVz
# dn:: uid=<uid>,ou=<JapaneseOU>,o=Airius

userpassword: {SHA}O3HSv1MusyL4kTjP+HKI5uxuNoM=
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
uid: rogasawara
mail: rogasawara@airius.co.jp
givenname;lang-ja:: 44Ot44OJ44OL44O8
# givenname;lang-ja:: <JapaneseGivenname>

sn;lang-ja:: 5bCP56yg5Y6f
# sn;lang-ja:: <JapaneseSn>

cn;lang-ja:: 5bCP56yg5Y6fIOODreODieODi+ODvA==
# cn;lang-ja:: <JapaneseCn>

title;lang-ja:: 5Za25qWt6YOoIOmDqOmVtw==
# title;lang-ja:: <JapaneseTitle>

preferredlanguage: ja
givenname:: 44Ot44OJ44OL44O8
# givenname:: <JapaneseGivenname>

sn:: 5bCP56yg5Y6f
# sn:: <JapaneseSn>

cn:: 5bCP56yg5Y6fIOODreODieODi+ODvA==
# cn:: <JapaneseCn>

title:: 5Za25qWt6YOoIOmDqOmVtw==
# title:: <JapaneseTitle>

givenname;lang-ja;phonetic:: 44KN44Gp44Gr44O8
# givenname;lang-ja;phonetic::

<JapaneseGivenname_in_phonetic_representation_kana>
sn;lang-ja;phonetic:: 44GK44GM44GV44KP44KJ
# sn;lang-ja;phonetic:: <JapaneseSn_in_phonetic_representation_kana>

cn;lang-ja;phonetic:: 44GK44GM44GV44KP44KJIOOCjeOBqeOBq+ODvA==
# cn;lang-ja;phonetic:: <JapaneseCn_in_phonetic_representation_kana>

title;lang-ja;phonetic:: 44GI44GE44GO44KH44GG44G2IOOBtuOBoeOCh+OBhg==
# title;lang-ja;phonetic::
# <JapaneseTitle_in_phonetic_representation_kana>

givenname;lang-en: Rodney
sn;lang-en: Ogasawara
cn;lang-en: Rodney Ogasawara
title;lang-en: Sales, Director

**Comment by skradel** [comment]
If you paste the LDIF in directly from the RFC page, it will not be formatted correctly due to the RFC's embedded formatting / linebreaks and will "correctly" fail on the line starting "&lt;JapaneseGivenname_in_phonetic_representation_kana&gt;".

**Comment by Casebash** [comment]
Deleted a new line and then it started working

**Comment by skradel** [comment]
Aye, the parser will choke on a non-continuation line containing no ':' character.  Considering throwing a custom exception in this case, rather than handing a -1 length to string.Substring.

**Comment by skradel** [comment]
We now get an ApplicationException noting the line number on a non-comment, non-blank, non-continuation line missing its ':'.
