### ISSUE TITLE
Parser doesn't allow empty DN name

### ISSUE THREAD

**Issue by Casebash** [skradel/Zetetic.Ldap#6]
Parser doesn't allow empty DN name. I don't think this is part of the actual standard, but Microsoft allows this.

DN:
changetype: modify
add: schemaUpdateNow
schemaUpdateNow: 1

I tried to fix this by changing the AddAttrValue `if (string.IsNullOrEmpty(attrName))` to `if (attrName==null)`.

Also. in the Read of LdifReader. I tried `string attrName = line.Substring(0, fc);` to `string attrName = fc==-1 ? "":line.Substring(0, fc);`. This didn't make it work - it only made it not crash

**Comment by skradel** [comment]
The parser will now tolerate a null DN without exploding, but various DN / RDN related things in Entry.cs will still have a problem with it.  The schema update instruction is common enough at the end of MSFT schema LDIFs that it's worthwhile to make parseable...
